export const resources = [
  { id: 'Deerfield', name: 'Deerfield', groupOnly: true },
  { id: 'FG-Deerfield', name: 'FG', parentId: 'Deerfield' },
  { id: 'K1-Deerfield', name: 'K1', parentId: 'Deerfield' },
  { id: 'K2-Deerfield', name: 'K2', parentId: 'Deerfield' },
  { id: 'K3-Deerfield', name: 'K3', parentId: 'Deerfield' },
  { id: 'K4-Deerfield', name: 'K4', parentId: 'Deerfield' },
  { id: 'MTP-Deerfield', name: 'MTP', parentId: 'Deerfield' },
  { id: 'REC-Deerfield', name: 'REC', parentId: 'Deerfield' },
  { id: 'Redwood City', name: 'Redwood City', groupOnly: true },
  { id: 'FG1-Redwood City', name: 'FG1', parentId: 'Redwood City' },
  { id: 'FG2-Redwood City', name: 'FG2', parentId: 'Redwood City' },
  { id: 'K1-Redwood City', name: 'K1', parentId: 'Redwood City' },
  { id: 'K2-Redwood City', name: 'K2', parentId: 'Redwood City' },
  { id: 'K3-Redwood City', name: 'K3', parentId: 'Redwood City' },
  { id: 'K4-Redwood City', name: 'K4', parentId: 'Redwood City' },
  { id: 'MTP-Redwood City', name: 'MTP', parentId: 'Redwood City' },
  { id: 'Old Bridge', name: 'Old Bridge', groupOnly: true },
  { id: 'FG-Old Bridge', name: 'FG', parentId: 'Old Bridge' },
  { id: 'FRB-Old Bridge', name: 'FRB', parentId: 'Old Bridge' },
  { id: 'K-Old Bridge', name: 'K', parentId: 'Old Bridge' },
  { id: 'RTD-E-Old Bridge', name: 'RTD-E', parentId: 'Old Bridge' },
  { id: 'MTP-Old Bridge', name: 'MTP', parentId: 'Old Bridge' },
  { id: 'REC-Old Bridge', name: 'REC', parentId: 'Old Bridge' },
  { id: 'R1-Old Bridge', name: 'R1', parentId: 'Old Bridge' },
  { id: 'REC-Redwood City', name: 'REC', parentId: 'Redwood City' },
  { id: 'Atlanta', name: 'Atlanta', groupOnly: true },
  { id: 'Azalea-Atlanta', name: 'Azalea', parentId: 'Atlanta' },
  { id: 'Chamblee-Atlanta', name: 'Chamblee', parentId: 'Atlanta' },
  { id: 'CLT-Atlanta', name: 'CLT', parentId: 'Atlanta' },
  { id: 'Dogwood-Atlanta', name: 'Dogwood', parentId: 'Atlanta' },
  { id: 'FG-Atlanta', name: 'FG', parentId: 'Atlanta' },
  { id: 'Magnolia-Atlanta', name: 'Magnolia', parentId: 'Atlanta' },
  { id: 'Dallas', name: 'Dallas', groupOnly: true },
  { id: 'FG-Dallas', name: 'FG', parentId: 'Dallas' },
  { id: 'K-Dallas', name: 'K', parentId: 'Dallas' },
  { id: 'MTP-Dallas', name: 'MTP', parentId: 'Dallas' },
  { id: 'REC-Dallas', name: 'REC', parentId: 'Dallas' },
  { id: 'REC-Atlanta', name: 'REC', parentId: 'Atlanta' },
  { id: 'Offsite', name: 'Offsite', groupOnly: true },
  { id: 'OFS-Offsite', name: 'OFS', parentId: 'Offsite' },
  { id: 'FC-Deerfield', name: 'FC', parentId: 'Deerfield' },
];
